---
  - file: 
      path: /opt/app/release/
      owner: apache
      group: apache
      state: directory
      mode: 0755
 
  - name: URL downlaod 
    unarchive:
      src: https://github.com/devopsdemoapps/devops-demo-app/archive/1.4.tar.gz
      dest: /opt/app/release
      owner: apache
      group: apache
      remote_src: yes
...
